### ISSUE TITLE
Merge SPM branch in to main

### ISSUE THREAD

**Issue by jagreenwood** [damuellen/xlsxwriter.swift#15]
Hi! Great work on this lib. I was wondering if there is a reason why the SPM branch shouldn't be merged in to main?
Reason I'm asking is these branches appear to have diverged more than just the way the `xlxswriter` library is included and it would be great to have a single source of truth.
I'd be happy to work on a PR to help things along.

**Comment by orchetect** [comment]
Yes, merge and tag a new release. I'm having issues in app builds where Xcode is refusing to compile because it doesn't like using the SPM branch in a package dependency.

**Comment by damuellen** [comment]
I have complied with your request. I created a tag before and after the merge.

**Comment by orchetect** [comment]
I don't see the merge. Main branch is the same as 10 months ago.

**Comment by orchetect** [comment]
Running into another issue when `xlsxwriter.swift` is used as a dependency. Xcode won't compile, citing that internal dependencies use unstable references. This is a bigger issue with the `libxlsxwriter` repo not having proper SemVer release tags, forcing us to use its main branch.

> "packages which use branch-based dependency requirements can't be added as dependencies to packages that use version-based dependency requirements; you should remove branch-based dependency requirements before publishing a version of your package."
> 
> [Apple docs](https://github.com/apple/swift-package-manager/blob/main/Documentation/PackageDescription.md#package-dependency-requirement)
