### ISSUE TITLE
Merging cells

### ISSUE THREAD

**Issue by CypriotUnknown** [damuellen/xlsxwriter.swift#2]
Hello. Does this library support merging cells? If so, how ?

**Comment by damuellen** [comment]
No, but I can expose the function if you need it.

**Comment by damuellen** [comment]
https://github.com/damuellen/xlsxwriter.swift/blob/050bd8b75d8733c3b4909264ec518743e588f895/Sources/xlsxwriter/Worksheet.swift#L171
