### ISSUE TITLE
Compile error related to xlsxwriter.h

### ISSUE THREAD

**Issue by trevor-sonic** [damuellen/xlsxwriter.swift#3]
Hi I've created a new project and import the library with SPM. But It is not compiling due to find `xlsxwriter.h`

```
#ifdef _WIN32
#include "C:/vcpkg/installed/x64-windows/include/xlsxwriter.h"
#elif __APPLE__
#include "/opt/homebrew/include/xlsxwriter.h" //   <- Here is indicating '/opt/homebrew/include/xlsxwriter.h' file not found
#elif __linux__
#include "/usr/local/include/xlsxwriter.h"
#endif
```

For sure I don't have home-brew installed on my machine. But I guess if I had installed it would work on my machine only not on the real hardware.
Is there any way to accomplish this requirement?

**Comment by damuellen** [comment]
If you don't want to install libxlsxwriter via homebrew, you can check out the tag 0.3.0, in that version libxlsxwriter is part of the package. Is the only change compared to 1.0.1.

**Comment by damuellen** [comment]
I just adjusted the header to distinguish between Apple Silicon and Intel macs.
