### ISSUE TITLE
Mistake in Cols Initializier

### ISSUE THREAD

**Issue by bdkjones** [damuellen/xlsxwriter.swift#6]
I could be wrong, but it looks like you're accidentally initializing the start and end of a column range to the same end index.

Additionally, the `init()` method accepts a `UInt32` for the first column index. That should be `UInt16` according to libxlsxwriter.

https://github.com/damuellen/xlsxwriter.swift/blob/f066c88a636d0d075e3772934c54665eaebbef85/Sources/xlsxwriter/Cell_Range.swift#L37

**Comment by damuellen** [comment]
Thanks for the hint, I have corrected the error now.
