### ISSUE TITLE
Incorrect URL Writing Causes Failure

### ISSUE THREAD

**Issue by bdkjones** [damuellen/xlsxwriter.swift#7]
This line is incorrect:

https://github.com/damuellen/xlsxwriter.swift/blob/25e1c3dc359e4f050cc5a7a286e758e887971ba1/Sources/xlsxwriter/Worksheet.swift#L98

Using `.path()` will return an empty string for URLs such as: `mailto:somebody@somewhere.com`. This empty string will cause libxlsxwriter to fail with a very cryptic error: "ignoring NULL function parameter". 

`mailto:` URLs are listed as explicitly supported by libxlsxwriter, so this wrapper should handle them correctly. To do that, use `.absoluteString()` on the URL instead of `.path()`. This works for all well-formed URIs that libxlswriter supports, as shown:
<img width="1052" alt="Screen Shot 2022-08-26 at 00 49 14" src="https://user-images.githubusercontent.com/926566/186851429-9f035855-b35c-4b1f-ba26-3b0c0df8bef1.png">

The behavior for other URIs, such as local filesystem URLs, is undefined.

**Comment by damuellen** [comment]
Good find, have already implemented your suggestion. Thank you.
Have tagged it version 1.0.2
